language: php
os: linux
php:
  - 7.2
  - 7.3
  - 7.4
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y -qq libssh2-1-dev
  - sudo pecl channel-update pecl.php.net
  - pecl install -f ssh2-1.2
  - php -m | grep ssh2
  - composer install --dev
