language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
  - touch /tmp/ignore
  - pecl install -f ssh2-beta < /tmp/ignore
  - echo "extension=ssh2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev